# fly.toml app configuration file generated for codev on 2023-11-11T20:40:52-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codev"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
