on:
  push:
    branches: main

name: HTMX thing Workflow

jobs:
  job:
    name: Run Server
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - run: bun build --target=bun ./src/index.tsx --outdir ./build
      - run: bun ./build/index.js
