on:
  push:
    branches: main

name: HTMX thing Workflow
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun build --target=bun ./src/index.tsx --outdir ./build
      - run: bun ./build/index.js
